const axios = require("axios");
const jsdom = require("jsdom");
const { JSDOM } = jsdom;

// Context
// Promise 관련 문제 getDocument에 await 걸면 Promise {<Pending>}

const bandSingers = [
    "가을방학",
    "가이아",
    "갤럭시 익스프레스",
    "검엑스",
    "검정치마",
    "게이트 플라워즈",
    "과매기",
    "구남과여라이딩스텔라",
    "국카스텐",
    "글렌 체크",
    "기프트",
    "김경호 밴드",
    "김일환과 저급한 탄생",
    "김창완 밴드",
    "나상현씨밴드",
    "나티",
    "나후",
    "너드커넥션",
    "내귀에 도청장치",
    "네미시스",
    "네스티요나",
    "넬",
    "노 리플라이",
    "노바소닉",
    "노브레인",
    "노라조",
    "님버스",
    "내적친분느끼는 중장년 쉽땡끼들",
    "다윗의 막장",
    "다크 미러 오브 트레지디",
    "달담",
    "당기시오",
    "더 넛츠",
    "더더",
    "더 락타이거즈",
    "더 바이퍼스",
    "더 보울스",
    "더 사운드",
    "더 크레센츠",
    "더 크로스",
    "더 히스테릭스",
    "더 포니",
    "데드버튼즈",
    "데스페라도",
    "데이브레이크",
    "데디오레디오",
    "더 로즈",
    "델리스파이스",
    "도로시 밴드",
    "도트",
    "동이혼",
    "디아블로",
    "디어클라우드",
    "디오니서스",
    "딕펑스",
    "드림캐쳐",
    "뜨거운 감자",
    "랄라스윗",
    "램넌츠 오브 더 폴른",
    "러브엑스테레오",
    "러브홀릭",
    "럭스",
    "럼블 피쉬",
    "레이니 썬",
    "레이지본",
    "레전드",
    "로로스",
    "로맨틱펀치",
    "로 바이 페퍼스",
    "로큰롤 라디오",
    "롤러코스터",
    "롤링쿼츠",
    "루싸이트 토끼",
    "루켄롤즈",
    "룩앤리슨",
    "리페어샵",
    "루나(LUNA)",
    "마그마(밴드)",
    "마이 앤트 메리",
    "마하트마",
    "매드 프렛",
    "메스그램",
    "메이트",
    "메탈라템",
    "모가비",
    "못",
    "몽구스",
    "몽니",
    "뮤즈그레인",
    "미로밴드",
    "뮤디",
    "바세린",
    "바이 바이 배드맨",
    "바투(밴드)",
    "백두산",
    "버스커 버스커",
    "버스터리드",
    "버즈",
    "벗",
    "베이비 블루",
    "베티애스",
    "벤치위레오",
    "보이즈 인 더 키친",
    "부활",
    "불나방스타쏘세지클럽",
    "불싸조",
    "뷰렛",
    "브로콜리 너마저",
    "브로큰티스",
    "브로큰 발렌타인",
    "브리즈",
    "블랙백",
    "블랙 신드롬",
    "블랙홀",
    "삐삐밴드",
    "사랑과 평화",
    "사막꽃",
    "사이드카",
    "사일런트 아이",
    "산울림",
    "삼청",
    "새닉",
    "새드 레전드",
    "새소년",
    "새크리파이스",
    "서태지 밴드",
    "세이수미",
    "셔츠 보이 프랭크",
    "셔틀루프",
    "선셋 온 더 브릿지",
    "소규모 아카시아 밴드",
    "소년:달",
    "소란",
    "솔루션스",
    "송골매",
    "술탄 오브 더 디스코",
    "스윗리벤지",
    "스토리셀러",
    "스톰(밴드)",
    "스트라이커스",
    "스트릿 건즈",
    "시나 쓰는 앨리스",
    "시나위",
    "시네마",
    "시베리안 허스키(록밴드)",
    "신스네이크",
    "신중현과 엽전들",
    "신촌블루스",
    "신현희와 김루트",
    "실리카겔",
    "쏜애플",
    "아디오스 오디오",
    "아레스",
    "아마도이자람밴드",
    "아스트로너츠",
    "아이즈",
    "아트 오브 파티스",
    "A-FRICA",
    "악퉁",
    "안녕바다",
    "알섬",
    "야다",
    "어어부밴드",
    "야채인간",
    "에고펑션에러",
    "에드훠",
    "엔플라잉",
    "예레미",
    "옐로우 몬스터즈",
    "오드리양장점",
    "오버헤드",
    "오지은과 늑대들",
    "옥상달빛",
    "올라이즈 밴드",
    "요정",
    "왓에버댓민즈",
    "원",
    "원위",
    "위치스",
    "유기농맥주",
    "유앤미블루",
    "음율",
    "이글루베이",
    "이디오테잎",
    "이슈타르",
    "익스",
    "인세인래틀즈",
    "자우림",
    "자유연상",
    "잔나비",
    "잔치잔치",
    "잠비나이",
    "재주소년",
    "적란운",
    "전기뱀장어",
    "제이레빗",
    "조용필과 위대한 탄생",
    "주주클럽",
    "줄리아하트",
    "지킬",
    "지하드",
    "중식이",
    "차세대",
    "차이나 몽키 브레인",
    "청년실업",
    "체리필터",
    "초록불꽃소년단",
    "치즈스테레오",
    "칠보장",
    "카디",
    "코인 클래식",
    "쾅프로그램",
    "크라잉 넛",
    "크래쉬",
    "크랙실버",
    "크랜필드",
    "크로우",
    "크리포스",
    "타카피",
    "타임 콘체르토",
    "터치드",
    "톡식",
    "트랜스픽션",
    "파라솔",
    "파란노을",
    "페퍼톤스",
    "퍼플레인",
    "포(POE)",
    "폰부스",
    "품바 21",
    "프렌지",
    "플라워",
    "피싱걸스",
    "피터팬 컴플렉스",
    "피해의식(밴드)",
    "하비누아주",
    "한스밴드",
    "한음파",
    "할로우 잰",
    "해리빅버튼",
    "해머링",
    "허밍 어반 스테레오",
    "허클베리핀",
    "헤이즈",
    "혁오",
    "호피폴라",
    "홀리마쉬",
    "황신혜밴드",
    "히식스",
    "10CM",
    "18그램",
    "24아워즈",
    "3호선 버터플라이",
    "9와 숫자들",
    "achime",
    "AKMU",
    "Band ALLS",
    "Catch The Young",
    "CNBLUE",
    "DAY6",
    "Dragon Pony",
    "Every Single Day",
    "From The Airport",
    "FT아일랜드",
    "KlaFF",
    "GIRL",
    "Guyz",
    "H2O",
    "루아멜",
    "LUCY",
    "M.C The Max",
    "NELL",
    "N.EX.T",
    "O.O.O",
    "PITTA",
    "QWER",
    "skool",
    "SURL",
    "The Volunteers",
    "TOKKAEBI",
    "UNLASTING",
    "W24",
    "we hate jh",
    "Where The Story Ends",
    "Xdinary Heroes",
    "YB",
].map((el) => {
    return [el, "band"];
});

const trotSingers = [
    "강민주(가수)",
    "강진(가수)",
    "강혜연",
    "공훈",
    "김다현(트로트 가수)",
    "김소연(2004)",
    "김수희",
    "김연자",
    "김중연",
    "김태연(2012)",
    "김혜연(가수)",
    "김호중",
    "김희재",
    "나훈아",
    "남인수",
    "남진",
    "마아성",
    "민수현(가수)",
    "박상철",
    "박윤경",
    "박하이",
    "박현빈",
    "배호",
    "별사랑",
    "설운도",
    "소유미",
    "송가인",
    "송대관",
    "송해",
    "신승태",
    "심수봉",
    "쏘아",
    "안성훈",
    "양지은",
    "영탁",
    "오유진(2009)",
    "유지나(1968)",
    "윤수일",
    "윤태화",
    "은가은",
    "이미자",
    "이박사",
    "이찬원",
    "이혜리(가수)",
    "이호섭",
    "임영웅",
    "장민호",
    "장윤정",
    "전유진",
    "정동원",
    "정서주",
    "정희라",
    "조항조",
    "주현미",
    "진성(가수)",
    "태진아",
    "함중아",
    "허찬미",
    "현숙",
    "현인",
    "현철",
    "홍지윤",
    "홍진영",
    "황인선",
].map((el) => {
    return [el, "trot"];
});

const trotURL =
    "https://namu.wiki/w/%EB%B6%84%EB%A5%98:%ED%8A%B8%EB%A1%9C%ED%8A%B8%20%EA%B0%80%EC%88%98?namespace=%EB%AC%B8%EC%84%9C&cfrom=%EB%B0%A9%EC%8B%A4%EC%9D%B4";
const rockURL = "https://namu.wiki/w/록%20밴드/목록/한국";

const getDocument = async (url) => {
    const res = await axios.get(url);
    const dom = new JSDOM(res.data);
    return dom.window.document;
};

const getTrotSinger = async () => {
    try {
        // getDocument 함수가 완료될 때까지 기다림
        const document = await getDocument(trotURL);

        const arr = [];

        // 정확한 선택자 사용: 예제에서는 .Yry9Ar41 클래스의 div 요소를 선택
        Array.from(
            document.querySelector(".Yry9Ar41").querySelectorAll("div")
        ).forEach((el) => {
            const lists = Array.from(el.querySelectorAll("ul > li"));
            lists.forEach((el1) => {
                const name = el1.querySelector("a").textContent;
                arr.push(name);
            });
        });

        return arr;
    } catch (error) {
        console.error("Error fetching or parsing data:", error);
        return [];
    }
};

const getRockSingers = async () => {
    const document = await getDocument(rockURL);

    document
        .querySelectorAll(".hbU9WWgP")
        .forEach((el) => console.log(el.querySelector("a").textContent));
};

const getHipHopArtists = async () => {
    try {
        const url =
            "https://namu.wiki/w/%ED%9E%99%ED%95%A9/%EB%9E%98%ED%8D%BC%20%EB%B0%8F%20%ED%9E%99%ED%95%A9%20%EB%AE%A4%EC%A7%80%EC%85%98/%ED%95%9C%EA%B5%AD";

        const document = await getDocument(url);
        const artists = Array.from(document.querySelectorAll("a"))
            .filter((link) => link.href.startsWith("/w/"))
            .map((link) => link.textContent.trim());

        return artists;
    } catch (error) {
        console.error("Error fetching or parsing data:", error);
        return [];
    }
};

getHipHopArtists().then((artists) => {
    console.dir(artists, { maxArrayLength: null });
});

getRockSingers();

// 유튜브 플레이 리스트
// GET https://www.googleapis.com/youtube/v3/search
